version: 0.2
env:
    variables:
        NODE_ENV: test
        PORT: "8081"
        npm_config_force: true

phases:
  install:
    commands:
      - echo Installing dependency...
    #   - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
    #   - export NVM_DIR="$HOME/.nvm"
    #   - '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'
      - npm install -g npm@8.13.1
      - npm install -g node@16.15.1 --force
    #   - nvm install 16
    #   - nvm use 16
      - npm install -g yarn
      - npm install -g next
      - yarn
  build:
    commands:
      - echo Compiling the Node.js code      
      - yarn build
  post_build:
    commands:    
artifacts:
  files:
    - 'package.json'
    - 'build/**/*'