version: 0.2
env:
    variables:
        NODE_ENV: test
        PORT: "8081"       
phases:
    install:
        runtime-versions:
            nodejs: 12
        commands:            
            - "echo Entered the install phase..."
            - "npm install -g npm@latest"
            - "npm install --legacy-peer-deps"
            - "npm run build"
    pre_build:
        commands:
            - "echo Entered the prebuild phase..."
    post_build:
        commands:
            - "echo Entered the postbuild phase..."
            - "npm start"
artifacts:
    files:
        - package.json
        - "build/**/*"
        - config/**
        - constants/**
        - interfaces/**
        - middleware/**
        - pages/**
        - public/**
        - services/**
        - store/**
        - styles/**
        - utils/**
        - Axios.ts
        - next.config.js
        - tsconfig.json
