import { IPermission } from "../interfaces/permission";
import { IUser } from "../interfaces/user";

export const fakeUsers: Array<IUser> = [
  {
    pk: "49",
    email: "alanbmoore+testingusername@gmail.com",
    first_name: "Alan",
    last_name: "Moore",
    picture: null,
    license_number: "123456",
    company: "Latter & Blum",
    location: "New Orleans, LA, USA",
    phone_number: "(310) 526-3833",
    site_username: "testingusername",
    bio: "null",
    language: null,
    job_title: "null",
    instagram_data: null,
    instagram_connected: false,
    address: {
      longitude: -90.0782127,
      latitude: 29.9759983,
    },
    tags: null,
    is_on_boarding_completed: true,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
  {
    pk: "45",
    email: "tayyab.esketchers+az@gmail.com",
    first_name: "tayyab",
    last_name: "shahiud",
    picture: null,
    license_number: null,
    company: null,
    location: null,
    phone_number: null,
    site_username: null,
    bio: null,
    language: null,
    job_title: null,
    instagram_data: null,
    instagram_connected: false,
    address: null,
    tags: null,
    is_on_boarding_completed: false,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
  {
    pk: "47",
    email: "alanbmoore+requestinvitetest@gmail.com",
    first_name: "",
    last_name: "",
    picture: null,
    license_number: null,
    company: null,
    location: null,
    phone_number: null,
    site_username: null,
    bio: null,
    language: null,
    job_title: null,
    instagram_data: null,
    instagram_connected: false,
    address: null,
    tags: null,
    is_on_boarding_completed: false,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
  {
    pk: "33",
    email: "tayyab.esketchers+test123@gmail.com",
    first_name: "tayyab",
    last_name: "shahid",
    picture: null,
    license_number: null,
    company: null,
    location: null,
    phone_number: null,
    site_username: null,
    bio: null,
    language: null,
    job_title: null,
    instagram_data: null,
    instagram_connected: false,
    address: null,
    tags: null,
    is_on_boarding_completed: false,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
  {
    pk: "25",
    email: "joyw@kw.com",
    first_name: "Joy",
    last_name: "Woodruff",
    picture:
      "https://wickyick-profile-images.s3.amazonaws.com/images/profile/Screen_Shot_2022-03-14_at_10.32.59_AM.png?AWSAccessKeyId=AKIA4HZHURVQDBYE7KLN&Signature=rkrqNiDAvk7WILYctAEZYk8fWtU%3D&Expires=1655689573",
    license_number: "514230",
    company: "Keller Williams",
    location: "Tallahassee, FL, USA",
    phone_number: "(850) 509-9802",
    site_username: "null",
    bio: "I sell Florida homes.",
    language: null,
    job_title: "Broker",
    instagram_data: null,
    instagram_connected: false,
    address: {
      longitude: -84.2809332,
      latitude: 30.4380832,
    },
    tags: null,
    is_on_boarding_completed: false,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
  {
    pk: "34",
    email: "tayyab.esketchers+test1@gmail.com",
    first_name: "s",
    last_name: "s",
    picture: null,
    license_number: null,
    company: null,
    location: null,
    phone_number: null,
    site_username: null,
    bio: null,
    language: null,
    job_title: null,
    instagram_data: null,
    instagram_connected: false,
    address: null,
    tags: null,
    is_on_boarding_completed: false,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
  {
    pk: "1",
    email: "admin@gmail.com",
    first_name: "Alan",
    last_name: "Moore",
    picture: null,
    license_number: null,
    company: "Test",
    location: "New York",
    phone_number: null,
    site_username: null,
    bio: null,
    language: null,
    job_title: null,
    instagram_data: {},
    instagram_connected: false,
    address: {
      longitude: -74.0060152,
      latitude: 40.7127281,
    },
    tags: null,
    is_on_boarding_completed: false,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
  {
    pk: "35",
    email: "tayyab.esketchers+12@gmail.com",
    first_name: "s",
    last_name: "s",
    picture: null,
    license_number: null,
    company: null,
    location: null,
    phone_number: null,
    site_username: null,
    bio: null,
    language: null,
    job_title: null,
    instagram_data: null,
    instagram_connected: false,
    address: null,
    tags: null,
    is_on_boarding_completed: false,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
  {
    pk: "36",
    email: "tayyab.esketchers+t12@gmail.com",
    first_name: "s",
    last_name: "ss",
    picture: null,
    license_number: null,
    company: null,
    location: null,
    phone_number: null,
    site_username: null,
    bio: null,
    language: null,
    job_title: null,
    instagram_data: null,
    instagram_connected: false,
    address: null,
    tags: null,
    is_on_boarding_completed: false,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
  {
    pk: "42",
    email: "tayyab.shahid7+12221sd3@gmail.com",
    first_name: "",
    last_name: "",
    picture: null,
    license_number: null,
    company: null,
    location: null,
    phone_number: null,
    site_username: null,
    bio: null,
    language: null,
    job_title: null,
    instagram_data: null,
    instagram_connected: false,
    address: null,
    tags: null,
    is_on_boarding_completed: false,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
  {
    pk: "37",
    email: "tayyab.esketchers@gmai.com",
    first_name: "",
    last_name: "",
    picture: null,
    license_number: null,
    company: null,
    location: null,
    phone_number: null,
    site_username: null,
    bio: null,
    language: null,
    job_title: null,
    instagram_data: null,
    instagram_connected: false,
    address: null,
    tags: null,
    is_on_boarding_completed: false,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
  {
    pk: "39",
    email: "tayyab.esketchers+123@gmail.com",
    first_name: "",
    last_name: "",
    picture: null,
    license_number: null,
    company: null,
    location: null,
    phone_number: null,
    site_username: null,
    bio: null,
    language: null,
    job_title: null,
    instagram_data: null,
    instagram_connected: false,
    address: null,
    tags: null,
    is_on_boarding_completed: false,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
  {
    pk: "30",
    email: "tayyab.shahid11@gmail.com",
    first_name: "tayyab",
    last_name: "shahid",
    picture: null,
    license_number: "123",
    company: null,
    location: null,
    phone_number: null,
    site_username: null,
    bio: null,
    language: null,
    job_title: null,
    instagram_data: {
      instagram_user_id: 17841400182068424,
      instagram_user_name: "ig.tayoshahid",
      instagram_profile_url: "https://www.instagram.com/ig.tayoshahid",
      instagram_access_token:
        "IGQVJWWlVNNXp6cUViSG1ZAb21hTFFJdzBuR29LNTFrbV93b2dadjR5dmZA6U0Uya19nVXR5M0ZAyelNEVTZAGd04wbVZAlUnlTSUZAGU1JWSTlqM1ZAGVjZAhM1RYNjcwOGRXNlNkQW9wUDZAR",
    },
    instagram_connected: true,
    address: null,
    tags: null,
    is_on_boarding_completed: false,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
  {
    pk: "40",
    email: "tayyab.shahid7+123@gmail.com",
    first_name: "",
    last_name: "",
    picture: null,
    license_number: null,
    company: null,
    location: null,
    phone_number: null,
    site_username: null,
    bio: null,
    language: null,
    job_title: null,
    instagram_data: null,
    instagram_connected: false,
    address: null,
    tags: null,
    is_on_boarding_completed: false,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
  {
    pk: "41",
    email: "tayyab.shahid7+1221sd3@gmail.com",
    first_name: "",
    last_name: "",
    picture: null,
    license_number: null,
    company: null,
    location: null,
    phone_number: null,
    site_username: null,
    bio: null,
    language: null,
    job_title: null,
    instagram_data: null,
    instagram_connected: false,
    address: null,
    tags: null,
    is_on_boarding_completed: false,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
  {
    pk: "43",
    email: "tayyab.shahid7+122sd21sd3@gmail.com",
    first_name: "",
    last_name: "",
    picture: null,
    license_number: null,
    company: null,
    location: null,
    phone_number: null,
    site_username: null,
    bio: null,
    language: null,
    job_title: null,
    instagram_data: null,
    instagram_connected: false,
    address: null,
    tags: null,
    is_on_boarding_completed: false,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
  {
    pk: "44",
    email: "tayyab.shahid7+123ss@gmail.com",
    first_name: "",
    last_name: "",
    picture: null,
    license_number: "12as",
    company: null,
    location: null,
    phone_number: null,
    site_username: null,
    bio: null,
    language: null,
    job_title: null,
    instagram_data: null,
    instagram_connected: false,
    address: null,
    tags: null,
    is_on_boarding_completed: false,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
  {
    pk: "46",
    email: "tayyab.shahid7+az@gmail.com",
    first_name: "",
    last_name: "",
    picture: null,
    license_number: null,
    company: null,
    location: null,
    phone_number: null,
    site_username: null,
    bio: null,
    language: null,
    job_title: null,
    instagram_data: null,
    instagram_connected: false,
    address: null,
    tags: null,
    is_on_boarding_completed: false,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
  {
    pk: "24",
    email: "tayyab.esketchers+test123vb@gmail.com",
    first_name: "Tayyab",
    last_name: "Shahid",
    picture:
      "https://wickyick-profile-images.s3.amazonaws.com/images/profile/test_qquUmev.png?AWSAccessKeyId=AKIA4HZHURVQDBYE7KLN&Signature=iAfQKZHPoYvmNiQxAmALBwi6700%3D&Expires=1655689574",
    license_number: "0900",
    company: "Esketchers",
    location: "New York, NY, USA",
    phone_number: "(123) 123-1231",
    site_username: "null",
    bio: "null",
    language: "Abkhazian",
    job_title: "null",
    instagram_data: {
      instagram_user_id: 17841400182068424,
      instagram_user_name: "ig.tayoshahid",
      instagram_profile_url: "https://www.instagram.com/ig.tayoshahid",
      instagram_access_token:
        "IGQVJYcTV3MGduVEI0ZA0NVd1dpd21LMFZAKY0ZAtMDFia001dWc0dmtzY0FvNS1NeDFMYTl2ZAzNUX1dkSFZAzdFp4OUNtdHRSS3pDeWxCWG5YT1M0MDl6TlVWLTlVM1JoMEhQSzhCbjVR",
    },
    instagram_connected: true,
    address: {
      longitude: -74.0060152,
      latitude: 40.7127281,
    },
    tags: "tayyab",
    is_on_boarding_completed: true,
    is_verified: true,
    agent_followed: [
      {
        id: 3,
        user: 31,
        agent: 24,
      },
    ],
    agent_liked: [],
    experience: "2022-10-01T08:41:34Z",
    role: "Premium",
  },
  {
    pk: "50",
    email: "alanbmoore+requestinvite@gmail.com",
    first_name: "",
    last_name: "",
    picture: null,
    license_number: null,
    company: null,
    location: null,
    phone_number: null,
    site_username: null,
    bio: null,
    language: null,
    job_title: null,
    instagram_data: null,
    instagram_connected: false,
    address: null,
    tags: null,
    is_on_boarding_completed: false,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
  {
    pk: "51",
    email: "alanbmoore+testinginviterequest@gmail.com",
    first_name: "",
    last_name: "",
    picture: null,
    license_number: null,
    company: null,
    location: null,
    phone_number: null,
    site_username: null,
    bio: null,
    language: null,
    job_title: null,
    instagram_data: null,
    instagram_connected: false,
    address: null,
    tags: null,
    is_on_boarding_completed: false,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
  {
    pk: "29",
    email: "tayyab.shahid@toptal.com",
    first_name: "Tayyab",
    last_name: "Shahid",
    picture:
      "https://wickyick-profile-images.s3.amazonaws.com/images/profile/test_Dq30X6g.png?AWSAccessKeyId=AKIA4HZHURVQDBYE7KLN&Signature=EPUMuzFlC%2FaPfoOfh8NVMo0Qqs8%3D&Expires=1655689574",
    license_number: "1255",
    company: "abc",
    location: "New York, NY, USA",
    phone_number: "(123) 123-1231",
    site_username: "@test",
    bio: "fg",
    language: "Abkhazian",
    job_title: "test",
    instagram_data: null,
    instagram_connected: false,
    address: {
      longitude: -74.0060152,
      latitude: 40.7127281,
    },
    tags: null,
    is_on_boarding_completed: false,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: "2016-05-01T00:00:00Z",
    role: "Premium",
  },
  {
    pk: "52",
    email: "alanbmoore+requestinvitemonday@gmail.com",
    first_name: "",
    last_name: "",
    picture: null,
    license_number: null,
    company: null,
    location: null,
    phone_number: null,
    site_username: null,
    bio: null,
    language: null,
    job_title: null,
    instagram_data: null,
    instagram_connected: false,
    address: null,
    tags: null,
    is_on_boarding_completed: false,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
  {
    pk: "26",
    email: "tayyab.shahid7@gmail.com",
    first_name: "tayyab",
    last_name: "shahid",
    picture: null,
    license_number: null,
    company: null,
    location: null,
    phone_number: null,
    site_username: null,
    bio: null,
    language: null,
    job_title: null,
    instagram_data: null,
    instagram_connected: false,
    address: null,
    tags: null,
    is_on_boarding_completed: false,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
  {
    pk: "53",
    email: "tayyab.shahid7+test123@gmail.com",
    first_name: "",
    last_name: "",
    picture: null,
    license_number: null,
    company: null,
    location: null,
    phone_number: null,
    site_username: null,
    bio: null,
    language: null,
    job_title: null,
    instagram_data: null,
    instagram_connected: false,
    address: null,
    tags: null,
    is_on_boarding_completed: false,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
  {
    pk: "59",
    email: "alanbmoore+may11@gmail.com",
    first_name: "",
    last_name: "",
    picture: null,
    license_number: null,
    company: null,
    location: null,
    phone_number: null,
    site_username: null,
    bio: null,
    language: null,
    job_title: null,
    instagram_data: null,
    instagram_connected: false,
    address: null,
    tags: null,
    is_on_boarding_completed: false,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
  {
    pk: "60",
    email: "tayyab.esketchers+897665@gmail.com",
    first_name: "",
    last_name: "",
    picture: null,
    license_number: null,
    company: null,
    location: null,
    phone_number: null,
    site_username: null,
    bio: null,
    language: null,
    job_title: null,
    instagram_data: null,
    instagram_connected: false,
    address: null,
    tags: null,
    is_on_boarding_completed: false,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
  {
    pk: "61",
    email: "alanbmoore+may11224455@gmail.com",
    first_name: "",
    last_name: "",
    picture: null,
    license_number: null,
    company: null,
    location: null,
    phone_number: null,
    site_username: null,
    bio: null,
    language: null,
    job_title: null,
    instagram_data: null,
    instagram_connected: false,
    address: null,
    tags: null,
    is_on_boarding_completed: false,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
  {
    pk: "55",
    email: "alanbmoore+requestinvitemay4@gmail.com",
    first_name: "",
    last_name: "",
    picture: null,
    license_number: null,
    company: null,
    location: null,
    phone_number: null,
    site_username: null,
    bio: null,
    language: null,
    job_title: null,
    instagram_data: null,
    instagram_connected: false,
    address: null,
    tags: null,
    is_on_boarding_completed: false,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
  {
    pk: "56",
    email: "emily.woodruff@gmail.com",
    first_name: "",
    last_name: "",
    picture: null,
    license_number: null,
    company: null,
    location: null,
    phone_number: null,
    site_username: null,
    bio: null,
    language: null,
    job_title: null,
    instagram_data: null,
    instagram_connected: false,
    address: null,
    tags: null,
    is_on_boarding_completed: false,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
  {
    pk: "58",
    email: "tayyab.shahid7+897665@gmail.com",
    first_name: "",
    last_name: "",
    picture: null,
    license_number: null,
    company: null,
    location: null,
    phone_number: null,
    site_username: null,
    bio: null,
    language: null,
    job_title: null,
    instagram_data: null,
    instagram_connected: false,
    address: null,
    tags: null,
    is_on_boarding_completed: false,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
  {
    pk: "62",
    email: "alanbmoore+may1122445566@gmail.com",
    first_name: "",
    last_name: "",
    picture: null,
    license_number: null,
    company: null,
    location: null,
    phone_number: null,
    site_username: null,
    bio: null,
    language: null,
    job_title: null,
    instagram_data: null,
    instagram_connected: false,
    address: null,
    tags: null,
    is_on_boarding_completed: false,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
  {
    pk: "64",
    email: "alanbmoore+may112244556699@gmail.com",
    first_name: "",
    last_name: "",
    picture: null,
    license_number: null,
    company: null,
    location: null,
    phone_number: null,
    site_username: null,
    bio: null,
    language: null,
    job_title: null,
    instagram_data: null,
    instagram_connected: false,
    address: null,
    tags: null,
    is_on_boarding_completed: false,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
  {
    pk: "65",
    email: "m.tayyab@gmail.com",
    first_name: "",
    last_name: "",
    picture: null,
    license_number: null,
    company: null,
    location: null,
    phone_number: null,
    site_username: null,
    bio: null,
    language: null,
    job_title: null,
    instagram_data: null,
    instagram_connected: false,
    address: null,
    tags: null,
    is_on_boarding_completed: false,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
  {
    pk: "71",
    email: "",
    first_name: "",
    last_name: "",
    picture: null,
    license_number: null,
    company: null,
    location: null,
    phone_number: null,
    site_username: null,
    bio: null,
    language: null,
    job_title: null,
    instagram_data: null,
    instagram_connected: false,
    address: null,
    tags: null,
    is_on_boarding_completed: false,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Basic",
  },
  {
    pk: "66",
    email: "alanbmoore+testing@wickyick.com",
    first_name: "Alan",
    last_name: "Moore",
    picture:
      "https://wickyick-profile-images.s3.amazonaws.com/images/profile/test_7EgH1Qr.png?AWSAccessKeyId=AKIA4HZHURVQDBYE7KLN&Signature=DsVJAq6e5gHNTSiHf6n3e3ws1aI%3D&Expires=1655689575",
    license_number: "123456",
    company: "Reve Realtors",
    location: "New Orleans, LA, USA",
    phone_number: "(888) 888-4254",
    site_username: "alanbmoore",
    bio: "I like jasmine on homes.",
    language: null,
    job_title: "Agent",
    instagram_data: null,
    instagram_connected: false,
    address: {
      longitude: -90.0782127,
      latitude: 29.9759983,
    },
    tags: "tulanealum,shotgunhomes,mardigras",
    is_on_boarding_completed: true,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
  {
    pk: "69",
    email: "mgriffin.jr@gmail.com",
    first_name: "Michael",
    last_name: "Griffin, Jr.",
    picture: null,
    license_number: null,
    company: null,
    location: null,
    phone_number: null,
    site_username: null,
    bio: null,
    language: null,
    job_title: null,
    instagram_data: null,
    instagram_connected: false,
    address: null,
    tags: null,
    is_on_boarding_completed: false,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
  {
    pk: "70",
    email: "alanbmoore+testy1@gmail.com",
    first_name: "",
    last_name: "",
    picture: null,
    license_number: null,
    company: null,
    location: null,
    phone_number: null,
    site_username: null,
    bio: null,
    language: null,
    job_title: null,
    instagram_data: null,
    instagram_connected: false,
    address: null,
    tags: null,
    is_on_boarding_completed: false,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
  {
    pk: "67",
    email: "alanbmoore@wickyick.com",
    first_name: "Alan",
    last_name: "Moore",
    picture: null,
    license_number: null,
    company: null,
    location: null,
    phone_number: null,
    site_username: null,
    bio: null,
    language: null,
    job_title: null,
    instagram_data: null,
    instagram_connected: false,
    address: null,
    tags: null,
    is_on_boarding_completed: false,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
  {
    pk: "31",
    email: "alanbmoore@gmail.com",
    first_name: "Alan",
    last_name: "Moore",
    picture:
      "https://wickyick-profile-images.s3.amazonaws.com/images/profile/test_TIS9RQ4.png?AWSAccessKeyId=AKIA4HZHURVQDBYE7KLN&Signature=r0RZShSZihMKupnbBQvliwlHogs%3D&Expires=1655689575",
    license_number: "BK514230",
    company: "Reve Realtors",
    location: "New Orleans, LA, USA",
    phone_number: "(310) 526-3833",
    site_username: "alanbmoore",
    bio: "I sell big houses in all neighborhoods.",
    language: "English",
    job_title: "Agent",
    instagram_data: {
      instagram_user_id: 17841401413300422,
      instagram_user_name: "alanbmoore",
      instagram_profile_url: "https://www.instagram.com/alanbmoore",
      instagram_access_token:
        "IGQVJVc3JDQm1oQWlQUEsyNFpBM250WFlWaXJYajJNdlJqdUI4ZAWYxQWo1aWhuaklOQXpfbkVuNl95UzlJMkpUUTZADclV5V2ZA3U2pTWDR4cnUtMG52N2RxUGRmZAE4yMGdQaHFJclFB",
    },
    instagram_connected: true,
    address: {
      longitude: -90.0782127,
      latitude: 29.9759983,
    },
    tags: "#lowergardendistrict,#harvardalum,#craftsman,#beachbungalow,#topseller",
    is_on_boarding_completed: true,
    is_verified: true,
    agent_followed: [
      {
        id: 4,
        user: 66,
        agent: 31,
      },
      {
        id: 5,
        user: 68,
        agent: 31,
      },
    ],
    agent_liked: [
      {
        id: 4,
        user: 68,
        agent: 31,
      },
    ],
    experience: "2010-06-01T18:10:48Z",
    role: "Premium",
  },
  {
    pk: "68",
    email: "alanbmoore+testy@gmail.com",
    first_name: "Alan",
    last_name: "Moore",
    picture: null,
    license_number: "123456",
    company: "Remax",
    location: "Los Angeles, CA, USA",
    phone_number: "(888) 888-8888",
    site_username: "null",
    bio: "I like ugly homes.",
    language: null,
    job_title: "Agent",
    instagram_data: null,
    instagram_connected: false,
    address: {
      longitude: -118.242766,
      latitude: 34.0536909,
    },
    tags: "spechomes,developer,mansions",
    is_on_boarding_completed: true,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
  {
    pk: "57",
    email: "alanbmoore@gmail.com",
    first_name: "",
    last_name: "",
    picture: null,
    license_number: null,
    company: null,
    location: null,
    phone_number: null,
    site_username: null,
    bio: null,
    language: null,
    job_title: null,
    instagram_data: null,
    instagram_connected: false,
    address: null,
    tags: null,
    is_on_boarding_completed: false,
    is_verified: false,
    agent_followed: [],
    agent_liked: [],
    experience: null,
    role: "Premium",
  },
];

export const fakePermissions: Array<IPermission> = [
  { type: "account", key: "email address", value: "Can add email address" },

  { type: "account", key: "email address", value: "Can change email address" },

  { type: "account", key: "email address", value: "Can delete email address" },

  { type: "account", key: "email address", value: "Can view email address" },

  {
    type: "account",
    key: "email confirmation",
    value: "Can add email confirmation",
  },

  {
    type: "account",
    key: "email confirmation",
    value: "Can change email confirmation",
  },

  {
    type: "account",
    key: "email confirmation",
    value: "Can delete email confirmation",
  },

  {
    type: "account",
    key: "email confirmation",
    value: "Can view email confirmation",
  },

  { type: "admin", key: "log entry", value: "Can add log entry" },

  { type: "admin", key: "log entry", value: "Can change log entry" },

  { type: "admin", key: "log entry", value: "Can delete log entry" },

  { type: "admin", key: "log entry", value: "Can view log entry" },

  { type: "auth", key: "group", value: "Can add group" },

  { type: "auth", key: "group", value: "Can change group" },

  { type: "auth", key: "group", value: "Can delete group" },

  { type: "auth", key: "group", value: "Can view group" },

  { type: "auth", key: "permission", value: "Can add permission" },

  { type: "auth", key: "permission", value: "Can change permission" },

  { type: "auth", key: "permission", value: "Can delete permission" },

  { type: "auth", key: "permission", value: "Can view permission" },

  { type: "authtoken", key: "Token", value: "Can add Token" },

  { type: "authtoken", key: "Token", value: "Can change Token" },

  { type: "authtoken", key: "Token", value: "Can delete Token" },

  { type: "authtoken", key: "Token", value: "Can view Token" },

  { type: "authtoken", key: "token", value: "Can add token" },

  { type: "authtoken", key: "token", value: "Can change token" },

  { type: "authtoken", key: "token", value: "Can delete token" },

  { type: "authtoken", key: "token", value: "Can view token" },

  { type: "contenttypes", key: "content type", value: "Can add content type" },

  {
    type: "contenttypes",
    key: "content type",
    value: "Can change content type",
  },

  {
    type: "contenttypes",
    key: "content type",
    value: "Can delete content type",
  },

  { type: "contenttypes", key: "content type", value: "Can view content type" },

  { type: "invitations", key: "invitation", value: "Can add invitation" },

  { type: "invitations", key: "invitation", value: "Can change invitation" },

  { type: "invitations", key: "invitation", value: "Can delete invitation" },

  { type: "invitations", key: "invitation", value: "Can view invitation" },

  { type: "sessions", key: "session", value: "Can add session" },

  { type: "sessions", key: "session", value: "Can change session" },

  { type: "sessions", key: "session", value: "Can delete session" },

  { type: "sessions", key: "session", value: "Can view session" },

  { type: "sites", key: "site", value: "Can add site" },

  { type: "sites", key: "site", value: "Can change site" },

  { type: "sites", key: "site", value: "Can delete site" },

  { type: "sites", key: "site", value: "Can view site" },

  {
    type: "socialaccount",
    key: "social account",
    value: "Can add social account",
  },
  {
    type: "socialaccount",
    key: "social account",
    value: "Can change social account",
  },
  {
    type: "socialaccount",
    key: "social account",
    value: "Can delete social account",
  },
  {
    type: "socialaccount",
    key: "social account",
    value: "Can view social account",
  },

  {
    type: "socialaccount",
    key: "social application",
    value: "Can add social application",
  },
  {
    type: "socialaccount",
    key: "social application",
    value: "Can change social application",
  },
  {
    type: "socialaccount",
    key: "social application",
    value: "Can delete social application",
  },
  {
    type: "socialaccount",
    key: "social application",
    value: "Can view social application",
  },
  {
    type: "socialaccount",
    key: "social application token",
    value: "Can add social application token",
  },
  {
    type: "socialaccount",
    key: "social application token",
    value: "Can change social application token",
  },
  {
    type: "socialaccount",
    key: "social application token",
    value: "Can delete social application token",
  },
  {
    type: "socialaccount",
    key: "social application token",
    value: "Can view social application token",
  },

  { type: "user", key: "FollowerList", value: "Can add FollowerList" },

  { type: "user", key: "FollowerList", value: "Can change FollowerList" },

  { type: "user", key: "FollowerList", value: "Can delete FollowerList" },

  { type: "user", key: "FollowerList", value: "Can view FollowerList" },

  { type: "user", key: "LikeList", value: "Can add LikeList" },

  { type: "user", key: "LikeList", value: "Can change LikeList" },

  { type: "user", key: "LikeList", value: "Can delete LikeList" },

  { type: "user", key: "LikeList", value: "Can view LikeList" },

  { type: "user", key: "User", value: "Can add User" },

  { type: "user", key: "User", value: "Can Comment" },

  { type: "user", key: "User", value: "Can Connect Social Media To Account" },

  { type: "user", key: "User", value: "Can Display  Name" },

  { type: "user", key: "User", value: "Can Display Company Name" },

  { type: "user", key: "User", value: "Can Display License #" },

  { type: "user", key: "User", value: "Can Display Location Or City" },

  { type: "user", key: "User", value: "Can Display Profile Photo" },

  {
    type: "user",
    key: "User",
    value: "Can Display Social Media Posts On Profile Page",
  },

  {
    type: "user",
    key: "User",
    value: "Can Invite Up To Two People To Wickyick",
  },

  { type: "user", key: "User", value: "Can Share Profile" },

  { type: "user", key: "User", value: "Cannot Get Followed" },

  { type: "user", key: "User", value: "Cannot Get Liked" },

  { type: "user", key: "User", value: "Cannot See Likes And Followers" },

  { type: "user", key: "User", value: "Can change User" },

  { type: "user", key: "User", value: "Create Medical Record" },

  { type: "user", key: "User", value: "Can delete User" },

  { type: "user", key: "User", value: "Can view User" },
];
